### ISSUE TITLE
Progress bar/Loader icon

### ISSUE THREAD

**Issue by IbtashamAlee** [BlackArcX/classx_vue#10]
**Loader**
Add loader while loading user data.

**Comment by nmanumr** [comment]
@IbtashamAlee thanks for showing your interest in the project. But the issue you opened could be more descriptive if you follow the issue templates provided. It looks like issue is missing some details.

The issue would be more helpful if you could specify the exact routes you are talking about. Because the app is not currently handling users in any way.

**Comment by IbtashamAlee** [comment]
**Is your feature request related to a problem? Please describe.**
When I click on a section like **FA18-BCS-B**, it takes some time to fetch details regarding that section. Furthermore when I click a particular course for example **CSC339** (Classes > FA18-BCS-B > **CSC339**), it also takes some time to fetch/load details of the course.

**Describe the solution you'd like**
What I would like you to do is, you should add a loader icon or a progressive bar whatever you would like, to show the progress for the content being loaded.

**Additional context**
These are the examples of my requested feature
**Loading icon/screen** => https://tailwindcomponents.com/component/full-page-overlay-loading-screen
**Progress bar** => https://tailwindcomponents.com/component/windows-10-fluent-design-progress-bar

**Comment by nmanumr** [comment]
@IbtashamAlee great feature I would love to have it. PR is also welcomed for this issue.

If I have to implement it I would love to have a progress bar (something like this: https://tailwindcomponents.com/component/windows-10-fluent-design-progress-bar) after the top header. Which will be activated whenever a route is changed and app is loading data for that route. For which we have to distinguish that if data is not loaded yet or the response is empty (i.e., should we show empty state). We can do this by adding a flag in the VueX store which will tell us that first response have been arrived (as described in #12 also).
