### ISSUE TITLE
Add an empty state UI instead of an empty screen

### ISSUE THREAD

**Issue by IbtashamAlee** [BlackArcX/classx_vue#12]
**Is your feature request related to a problem? Please describe.**
On these routes like  Classes > FA18-BCS-B > CSC301 > **Resources**) and (Classes > **FA18-BCS-A@LHR**), there is no data on these routes.
 

**Describe the solution you'd like**
We should add a message like **Nothing to see** here or **No content available** instead of a full empty screen.

**Additional context**
For example, have a look at this empty state UI design
![nothing](https://user-images.githubusercontent.com/48012712/93934433-981b1c00-fd3c-11ea-9e5e-c2e3de67dd52.png)

**Comment by nmanumr** [comment]
@IbtashamAlee Hi thank you for your interest. I'm glad to tell you that this feature is already under development. Here are some issues I'm facing while the implementation of this feature:

1. We need an illustration that is compatible with both dark and light themes. (or, have an illustration that we can make compatible with both)
2. We have to distinguish that if data is not loaded yet or the response is empty (i.e., should we show empty state). We can do this by adding a flag in the VueX store which will tell us that first response have been arrived.

The issue described in the frist point is fixed and we have found a good illustration from PluralSight design system. (would love to update it if you have another great illustration.)
For the second point, its not done yet and would love to accept PR for this also. #10 is also depended on this flag too, which make both #12 and #10 related issues
