### ISSUE TITLE
Loading icon issue

### ISSUE THREAD

**Issue by IbtashamAlee** [BlackArcX/classx_vue#13]
**Describe the bug**
When I open certain courses the loader keeps loading. 

**To Reproduce**
1. Go to 'https://classx.web.app/classes/FA18-BCS-D@LHR'
2. Click on 'Any course'
3. See error

**Expected behavior**
It should display no data available if there is no data in the current course or it should show available data. 

**Desktop (please complete the following information):**
 - OS: [ Manjaro ]
 - Browser [chrome]

**Comment by nmanumr** [comment]
Good catch @IbtashamAlee so it keeps loading when there is no resource available.

Will try to fix it will next release.
