### ISSUE TITLE
Update title on page change

### ISSUE THREAD

**Issue by lablnet** [BlackArcX/classx_vue#7]
**Is your feature request related to a problem? Please describe.**
On browsing the different section when i were looked to title i get confused... so i think it will better if the title update on page change.

**Describe the solution you'd like**
Change and update the title on page change.

**Describe alternatives you've considered**
We can use Vue Watchers to archive this.

**Comment by nmanumr** [comment]
Hi @lablnet, I'm glad that you discovered this project and contributed. This is definitely great to have a feature. But as the project is at very early stages, there are definitely a lot of different nitty-gritty details missing. And would love to have more contributions from your side.

As you already created a PR, let discuss more about this issue there.
